let urlMap = new Map([
  ['index', ''],
  ['quickstart', ''],
  ['badge', 'badge'],
  ['circle', 'circle'],
  ['icons', 'icons'],
  ['lazyload', 'lazyload'],
  ['progress', 'progress'],
  ['slider', 'slider'],
  ['spinner', 'spinner'],
  ['swipe', 'swipe'],
  ['button', 'button'],
  ['check_list', 'checklist'],
  ['input', 'input'],
  ['number_spinner', 'number-spinner'],
  ['radio', 'radio'],
  ['switch', 'switch'],
  ['textarea', 'textarea'],
  ['preview', 'preview'],
  ['action_sheet', 'actionsheet'],
  ['dialog', 'dialog'],
  ['indicator', 'indicator'],
  ['infinite_scroll', 'infinite-scroll'],
  ['toast', 'toast'],
  ['top_tips', 'top-tips'],
  ['picker', 'picker'],
  ['datetime_picker', 'datetime-picker'],
  ['header', 'header'],
  ['navbar', 'navbar'],
  ['tabbar', 'tabbar'],
  ['search', 'search'],
  ['cell', 'cell'],
  ['cell_swipe', 'cell-swipe'],
  ['flex', 'flex'],
  ['footer', 'footer'],
  ['grid', 'grid'],
  ['loadmore', 'loadmore'],
  ['panel', 'panel'],
  ['popup', 'popup'],
  ['troubleshooting', ''],
  ['contributing', '']
])

export default urlMap
